import '../models/card.dart';
import '../models/deck.dart';

List<Deck> userDeck = [
  Deck(id: '0', title: 'Unit 1'),
  Deck(id: '1', title: 'Unit 2'),
  Deck(id: '2', title: 'Unit 3'),
  Deck(id: '3', title: 'Unit 4'),
  Deck(id: '4', title: 'Unit 5'),
  Deck(id: '5', title: 'Unit 6'),
  Deck(id: '6', title: 'Unit 7'),
  Deck(id: '7', title: 'Unit 8'),
  Deck(id: '8', title: 'Unit 9'),
];

List<Flash_Card> userFlashCard = [
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '101',
    front: '好む',
    hiraganaReading: 'このむ',
    hanChineseReading: 'HẢO',
    meaning: 'Thích',
    example:
        '1)一般にお年 寄りはあっさりした味を好む 。\nNhững người già thường thích đồ ăn có vị thanh đạm .\n2)納豆は嫌いではありませんが、好んでは食べません。 \nKhông phải là ghét món đậu phụ mà cho dù có thích thì cũng không ăn được.\n3)この薬には、虫の好まない成分が含まれている \nTrong thuốc này bao gồm các thành phần mà bọn côn trùng không thích.\n4)人の好みはそれぞれ違う。\nSở thích của mỗi người là khác nhau. \n5)彼女は誰からも好まれている。\nAi cũng thích cô ấy.\n',
    deck: '0',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '102',
    front: '嫌う',
    hiraganaReading: 'きらう',
    hanChineseReading: 'HIỀM',
    meaning: 'Ghét, không ưa',
    example:
        '1）彼女は彼を嫌っているようです。\nCô ấy có vẻ ghét anh ta.\n2）そんなことをしたら恋人に嫌われるよ。\nNếu làm những điều như thế thì sẽ bị người yêu ghét đấy .\n3）この植物は乾 燥を嫌う。\nLoài thực vật này không ưa khô hạn.\n',
    deck: '0',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '103',
    front: '願う',
    hiraganaReading: 'ねがう',
    hanChineseReading: 'NGUYỆN',
    meaning: 'Cầu mong',
    example:
        '1)世界平和を願う。 \nCầu mong thế giới (được/luôn) hòa bình.\n2)あなたの健康と成功を願っています。\nTôi cầu mong bạn mạnh khỏe và thành công.\n3)もう一度お願いします。\nXin hãy nói lại/làm lại một lần nữa.\n',
    deck: '0',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '104',
    front: '甘える',
    hiraganaReading: 'あまえる',
    hanChineseReading: 'CAM',
    meaning: 'Làm nũng',
    example:
        '1）子供が母親に甘える。\n Trẻ con làm nũng bố mẹ.\n2）どうぞ、この傘をお使いください。では、お言葉に甘えまして。。。\nXin hãy dùng chiếc ô này. Vậy thì tôi không khách sáo nữa\n',
    deck: '0',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '105',
    front: 'かわいがる',
    hiraganaReading: '',
    hanChineseReading: '',
    meaning: 'Chiều chuộng, nâng niu, ưu ái',
    example:
        '1）息子は妹をとてもかわいがっている。\nCon trai tôi rất chiều chuộng em gái.\n2）彼は上司にかわいがれている。\nAnh ta được cấp trên ưu ái.\n',
    deck: '0',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '106',
    front: '気づく',
    hiraganaReading: 'きづく',
    hanChineseReading: 'KHÍ',
    meaning: 'Nhận ra, phát hiện ra, tỉnh lại',
    example:
        '1)犯人は刑事に気づいて、逃げてしまった。\nTên tội phạm sau khi phát hiện ra cảnh sát hình sự đã bỏ chạy.\n2) ゲームに夢中だったので、父が帰ってきたことにも気づかなかった。\nVì quá mải mê chơi game nên tôi thậm chí chẳng nhận ra là bố đã về. \n3) 車にはねられ、気づいたときは病院のベードの上だった。\nTôi bị xe đâm, khi tỉnh lại thì thấy mình đã ở trên giường của bệnh viện.\n',
    deck: '0',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '107',
    front: '疑う',
    hiraganaReading: 'うたがう',
    hanChineseReading: 'NGHI',
    meaning: 'Nghi ngờ',
    example:
        '1)警察は私を犯人ではないかと疑っているらしい。\nCảnh sát hình như đang nghi ngờ không biết tôi có phải là tội phạm hay không.\n 2) 小さいな子供は人を疑うことを知らない。\nTrẻ con thì không biết nghi ngờ người khác.\n3) 私は彼の成功を疑ったことはない。\nTôi chưa bao giờ nghi ngờ sự thành công của anh ấy.\n4) ありえない光景を見て、自分の目を疑った。\nNhìn thấy quang cảnh không thể tưởng tượng nổi, tôi đã không tin vào mắt mình.\n',
    deck: '0',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '108',
    front: '苦しむ',
    hiraganaReading: 'くるしむ',
    hanChineseReading: 'KHỔ',
    meaning: 'Khổ, vất vả',
    example:
        '1) 学校で虐められて苦しんでいる子供が大勢いる。\nRất nhiều trẻ em đang khổ sở vì bị bắt nạt ở trường học.\n2) 私は長年腰痛に苦しんでいた。\nTôi đã khổ sở vì đau lưng nhiều năm nay.\n3) 父は家族を大切にせず、 母を苦しめた。\nBố không trân trọng gia đình và luôn làm mẹ khổ sở.\n',
    deck: '0',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '109',
    front: '悲しむ',
    hiraganaReading: 'かなしむ',
    hanChineseReading: 'BI',
    meaning: 'Đau khổ',
    example:
        '娘はペットの死を悲しんで、一日中泣いていた。\nCon gái tôi đau khổ vì thú cưng chết nên đã khóc suốt cả một ngày.\n',
    deck: '0',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '110',
    front: 'がっかりする',
    hiraganaReading: 'がっかりする',
    hanChineseReading: '',
    meaning: 'Thất vọng',
    example:
        '1)試験に落ちて、がっかりした。\nTôi thất vọng vì thi trượt.\n2)この結果にはがっかりしている*がっかりだ。\nTôi thất vọng về kết quả này.\n',
    deck: '0',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '111',
    front: '励ます',
    hiraganaReading: 'はげます',
    hanChineseReading: '',
    meaning: 'Động viên, an ủi',
    example:
        '1)受験に失敗した友人を励ました。\nTôi đã động viên đứa bạn vừa thi trượt.\n2) 皆さんの応援に励まされました。\nTôi đã được khích lệ bằng sự cổ vũ của mọi người.\n',
    deck: '0',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '112',
    front: '頷く',
    hiraganaReading: 'うなずく',
    hanChineseReading: '',
    meaning: '1) Gật đầu  2) Đồng ý',
    example:
        '1) 祖父は何も言わずに頷いた。\nÔng đã gật đầu mà chẳng nói gì cả.\n2) 何度頼んでも、父は頷いてくれない。\nDù nhiều lần nhờ vả mà bố chẳng chịu đồng ý.\n',
    deck: '1',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '113',
    front: '張り切る',
    hiraganaReading: 'はりきる',
    hanChineseReading: '',
    meaning: '1) Hăm hở,háo hức.  2) Hăng hái,chăm chỉ làm gì đó',
    example:
        '1) 入社第一日目、娘は張り切って出勤した。\nNgày đầu tiên vào công ty, con gái tôi đã rất hăng hái đi làm.\n2) 今年も運動会で優勝しようと、クラス全員張り切っている。\nĐể năm nay cũng vô địch tại hội thi thể thao, cả lớp đang rất hăng hái.\n',
    deck: '1',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '114',
    front: '威張る',
    hiraganaReading: 'いばる',
    hanChineseReading: '',
    meaning: '1) Kiêu ngạo, kiêu căng  2) Chảnh, hợm hĩnh',
    example:
        '自分ができるからと言って、すぐに威張る人は嫌われる\nChỉ vì bản thân làm được, những người kiêu căng ngay lập tức bị ghét.\n',
    deck: '1',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '115',
    front: '怒鳴る',
    hiraganaReading: 'どなる',
    hanChineseReading: '',
    meaning: 'Gào lên, hét lên (tâm trạng bực tức)',
    example:
        '1) そんなに大声で怒鳴らなくても聞こえますよ。\nKhông cần phải gào to lên như thế, tôi nghe thấy mà.\n2) 父親に「出て行け!」と怒鳴られた。\nTôi bị bố la: Cút ra ngoài\n',
    deck: '1',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '116',
    front: '暴れる',
    hiraganaReading: 'あばれる',
    hanChineseReading: 'BẠO',
    meaning: 'quậy phá',
    example:
        '1) 弟は気に 短く、子供の頃はすぐに暴れて、よく物を壊したものだ。\nThằng em tôi thì nóng tính, hồi còn bé cứ nổi giận là nó thường xuyên đập\nphá đồ.\n2) 酒に酔って暴れるなんて最低だと思う。\nTớ nghĩ say rượu rồi quậy quá là cái thứ tồi nhất đấy.\n',
    deck: '1',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '117',
    front: 'しゃがむ',
    hiraganaReading: 'しゃがむ',
    hanChineseReading: '',
    meaning: 'ngồi xổm',
    example:
        '子供が道にしゃがんで地面の虫を見ている。\nBọn trẻ con thì ngồi xổm ở đường để xem những con sâu trên mặt đất.\n',
    deck: '1',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '118',
    front: '退く',
    hiraganaReading: 'どく',
    hanChineseReading: '',
    meaning: 'tránh né',
    example: 'ちょっとそこをどいてください。\nXin hãy tránh chỗ đó ra 1chút.\n',
    deck: '1',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '119',
    front: '退ける',
    hiraganaReading: 'どける',
    hanChineseReading: '',
    meaning: 'dọn dẹp',
    example:
        '1) 通行の邪魔になるので、自転車を歩道から退けてください。\nCản trở đi lại đấy, hãy dọn cái xe đạp ra khỏi đường đi bộ.\n2) 机の上に積んだ本をわきに退けて仕事をした。\nĐám sách chất trên bàn thì dẹp qua một bên rồi làm việc.\n',
    deck: '1',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '120',
    front: '被る',
    hiraganaReading: 'かぶる',
    hanChineseReading: '',
    meaning: 'đội, ,mang,che',
    example:
        '1)帽子を被る。\nĐội mũ.\n2) 頭から水を被る。\nDội nước từ đầu xuống.\n3) 父親は子供の罪を被って刑務所に入った。\nÔng bố đã phải vào tù vì chịu tội thay con (bao che).\n',
    deck: '2',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '121',
    front: 'かぶせる',
    hiraganaReading: 'かぶせる',
    hanChineseReading: '',
    meaning: 'che đậy,trùm lên',
    example:
        '1)ぬれないように、自転車にシートをかぶせておいた\nĐể không ướt, tôi đã che bạt lên xe đạp.\n人に罪をかぶせるなんて、ひどい人間\nĐổ lỗi cho người khác như thế, thật là người tồi tệ.\n',
    deck: '2',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '122',
    front: 'かじる',
    hiraganaReading: 'かじる',
    hanChineseReading: '',
    meaning: 'cắn,gặm',
    example:
        '1)りんごを丸ごとかじる。\nTôi gặm vòng quanh quả táo.\n２）ねずみが 柱をかじって困る\nCon chuột nó gặm cái cột rất là khó chịu.\n３）若いころ、フランス語をかじったことがある。\nHồi trẻ, tôi có học tiếng Pháp.\n',
    deck: '2',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '123',
    front: '撃つ',
    hiraganaReading: 'うつ',
    hanChineseReading: '',
    meaning: 'bắn',
    example:
        '1)警官が犯人をピストルで撃った\nCảnh sát bắn tên tội phạm bằng súng lục.\n{銃/大砲...} を撃つ 。Bắn súng/ Bắn đại bác\n',
    deck: '2',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '124',
    front: '漕ぐ',
    hiraganaReading: 'こぐ',
    hanChineseReading: '',
    meaning: 'chèo,đạp<đạp thuyền>',
    example:
        '1)自転車(のペダル)を漕ぐ。 Đạp xe đạp.\n{ 船/ ブランコ...}をこぐ Chèo thuyền/ Đánh đu.\n',
    deck: '2',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '125',
    front: '敷く',
    hiraganaReading: 'しく',
    hanChineseReading: '',
    meaning: 'trải,lắp đặt,lát',
    example:
        '1)床にふとんを敷く。 \nTrải đệm xuống sàn nhà.\n２）桜の下にビニールシートを敷いて花見をした。\nTrải tấm nilon xuống dưới cây anh đào và ngắm hoa.\n３）国中に鉄道が敷かれている \nĐường sắt đã trải khắp đất nước.\n４）この国は軍政を敷いてい\nĐất nước này chế độ quân chính (chính quyền trong tay quân đội) đã\nchiếm lĩnh.( bao phủ).\n',
    deck: '2',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '126',
    front: 'つぐ',
    hiraganaReading: 'つぐ',
    hanChineseReading: '',
    meaning: '1) rót  2) xới',
    example:
        '1) 水をコップにつぐ。\n Rót nước vào cốc.\n2) 茶わんにご飯をつぐ。\n Xới cơm vào bát.\n',
    deck: '2',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '127',
    front: '配る',
    hiraganaReading: 'くばる',
    hanChineseReading: 'Phối',
    meaning: '1) phân phát  2) chú ý, để mắt, chu đáo',
    example:
        '1) 先生が生徒にプリントを配った。\n Giáo viên phân phát tài liệu cho học sinh.\n2) 駅前で新しい店のチラシを配っている。 \n Phát tờ rơi của cửa hàng mới ở trước nhà ga.\n3) 服装に気を配る。\n Chú ý tới trang phục.\n4) 教師はすべての学生に目を配ることが必だ。\n Giáo viên cần để mắt tới toàn bộ học sinh.\n5) あの人は気配りのある人だ。\n Người kia là người rất chu đáo, tỉ mỉ.\n',
    deck: '2',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '128',
    front: '放る',
    hiraganaReading: 'ほうる',
    hanChineseReading: 'Phóng',
    meaning: 'bỏ, vứt, ném',
    example:
        '1) ボールを放る。\n Ném bóng.\n2) ゴミ箱にゴミをほうり投げた。 \n Ném rác vào thùng rác.\n3) 日記をつける習 慣が続かず、 途中で放り出してしまった。\n Không tiếp tục thói quen viết nhật ký nữa mà bỏ dở giữa chừng.\n4) 私のことにまわないで。ほっといて。\n Đừng quan tâm đến tôi. Để tôi yên.\n',
    deck: '2',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '129',
    front: '掘る',
    hiraganaReading: 'ほる',
    hanChineseReading: 'Quật',
    meaning: 'đào, bới',
    example:
        '1) 地面に穴を掘る。\n Đào lỗ trên mặt đất.\n2) 井戸を掘る。\n Đào giếng\n3) 畑で芋を掘る。 \n Đào khoai tây ở ruộng.\n4) 化石燃料がほりつくされる日がいずれ来るだろう。\n Có lẽ sắp đến ngày nhiên liệu hóa thạch bị khai thác cạn kiệt.\n',
    deck: '2',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '130',
    front: 'まく',
    hiraganaReading: 'まく',
    hanChineseReading: '',
    meaning: '1) gieo  2) tưới  3) phát  4) cắt đuôi',
    example:
        '1) 畑に野菜の種をまく。 \n Gieo hạt giống rau trên ruộng.\n2) 庭に水をまく。 \n Tưới nước trong vườn.\n3) 節分の日に豆をまいた。\n Gieo hạt đậu vào ngày tiết phân.\n4) 駅前でビラをまいていた。 \n Phát tờ rơi quảng cáo trước nhà ga.\n5) 容疑者は刑事の尾行をうまくまいて逃げ去った。\n Kẻ tình nghi đã khéo léo cắt đuôi cảnh sát và bỏ trốn.\n',
    deck: '3',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '131',
    front: '計る.測る.量る',
    hiraganaReading: 'はかる',
    hanChineseReading: 'KẾ, TRẮC, LƯỢNG',
    meaning: '1) Cân  2) Đo',
    example:
        '1)お湯を入れて3分計る\n Bấm 3 phút sau khi cho nước nóng vào.\n2) ダムの 貯水量を量る \n Đo thể tích của đập nước.\n3) 山の高さを測る。\n Đo chiều cao của ngọn núi.\n4) 荷物の重さを量る。\n Cân nặng của hành lý.\n',
    deck: '3',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '132',
    front: '占う',
    hiraganaReading: 'うらなう',
    hanChineseReading: 'CHIÊM',
    meaning: 'Bói, chiêm nghiệm, dự đoán',
    example:
        '1) 来年の運勢を占ってもらった。\n Tôi đã được coi cho vận hạn của năm sau.\n2) 経済の動向を占うのは専門家にも難しい。\n Để dự đoán xu hướng kinh tế thì đối với chuyên gia cũng khó ..\n',
    deck: '3',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '133',
    front: '引っ張る',
    hiraganaReading: 'ひっぱる',
    hanChineseReading: 'DẪN, TRƯƠNG',
    meaning: 'Kéo',
    example:
        '1) この紐を引っ張ると電気がつく。\n Kéo cái dây này thì đèn sẽ sáng.\n2) おもちゃ売り場から離れない子供の手を 引っ張って、外に出た。\n Con tớ không chịu rời quầy bán đồ chơi, phải kéo tay nó đi ra ngoài.\n3) 新入生をたくさん、うちのクラブに引っ 張ってこよう。\n Hãy cùng kéo thật nhiều sinh viên năm nhất về với câu lạc bộ của chúng mình nào.\n',
    deck: '3',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '134',
    front: '突く',
    hiraganaReading: 'つく',
    hanChineseReading: 'ĐỘT',
    meaning: '1) Chống  2) Đâm, chọc',
    example:
        '1) 喧嘩して相手の胸を手で突い。\n Vì cãi nhau nên tôi đã dùng tay đẩy vào ngực của đối phương.\n2) フォークで肉を突く。\n Dùng dĩa để xiên thịt.\n3) 杖を突いて歩く。\n Chống gậy đi bộ.\n4) 転んでとっさに地面に手を突いた。\n Vì bị ngã nên ngay lập tức tớ chống tay xuống mặt đất.\n',
    deck: '3',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '135',
    front: '突き当たる',
    hiraganaReading: 'つきあたる',
    hanChineseReading: 'ĐỘT, ĐƯƠNG',
    meaning: '1) Đụng, va chạm  2) Đến chỗ tận cùng',
    example:
        '1) この道を真っすぐ行って、 突き当たったら左に曲がって下さい。\n Đi thẳng đường này, đến cuối đường thì rẽ trái.\n2) 計画は予算不足という問題に突き当た。\n Kế hoạch đã đụng phải vấn đề là thiếu dự toán (dự toán thiếu kinh phí,\nthiếu tiền).\n',
    deck: '3',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '136',
    front: '立ち止まる',
    hiraganaReading: 'たちどまる',
    hanChineseReading: 'LẬP, CHỈ',
    meaning: 'Đứng lại, dừng lại',
    example:
        '1. 道で声をかけられて立ち止まった\nĐang ở đường, vì bị gọi nên tớ đã dừng lại.\n2. 自分の人生はこのままでいいのか、少し立ち止まって考えてみたい\nCuộc đời của bản thân, cứ như hiện tại có tốt hay không? Tớ muốn dừng\nlại 1 chút và thử suy nghĩ\n',
    deck: '3',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '137',
    front: '近寄る',
    hiraganaReading: 'ちかよる',
    hanChineseReading: 'CẬN, KÍ',
    meaning: 'Tiếp cận, tới gần',
    example:
        '1. 物音がしたので窓に近 寄って外を見た\nVì nghe thấy tiếng lạ nên tớ đã tới gần cửa sổ và nhìn ra ngoài.\n2. この川は危険なので近 寄らないでください\nCon sông này vì nguy hiểm nên không được lại gần.\n',
    deck: '3',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '138',
    front: '横切る',
    hiraganaReading: 'よこぎる',
    hanChineseReading: 'HOÀNH, THIẾT',
    meaning: 'Đi ngang, vượt qua',
    example:
        '1. 道を横切って 向こう側に渡った\nVượt qua đường để sang phía bên kia.\n2. 何か黒いものが視界を横切った\nCó cái gì đen đủi đã vượt qua tầm nhìn.\n',
    deck: '3',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '139',
    front: '転ぶ',
    hiraganaReading: 'ころぶ',
    hanChineseReading: 'CHUYỂN',
    meaning: 'Ngã, té',
    example:
        '1. 雪道で滑って転んでしまった\nTớ đã té vì trượt ở đường tuyết.\n2. 状況がどう転んでも、この計画には影響はない。\nDù bối cảnh có đi theo chiều hướng nào thì đối với kế hoạch này cũng\nkhông ảnh hưởng\n',
    deck: '3',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '140',
    front: '躓く',
    hiraganaReading: 'つまずく',
    hanChineseReading: 'CHÍ',
    meaning: 'vấp',
    example:
        '1)道で石につまずいて転んでしまった。\nTớ bị ngã vì vấp viên đá ở đường .\n２)映画製作は、 資金集めの段階でつまずいている。\nViệc làm phim đang bị vấp ở giai đoạn thu gom vốn.\n',
    deck: '4',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '141',
    front: 'ひく',
    hiraganaReading: 'ひく',
    hanChineseReading: '',
    meaning: 'chèn, cán qua',
    example:
        '1)車にひかれて骨折した。 \nTôi bị gẫy xương vì đâm phải xe ô tô.\n2)線路内に入り込んで遊んでいた子供が電車に引かれて死亡した。\nĐứa trẻ chơi trong khu vực đường ray bị chết do bị tàu điện đâm phải .\n',
    deck: '4',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '142',
    front: '溺れる',
    hiraganaReading: 'おぼれる',
    hanChineseReading: 'NỊCH',
    meaning: 'Chết đuối/ đuối nước,   sa vào',
    example:
        '1)川に落ちて溺れている子供を助けた。\nCứu đứa trẻ bị đuối nước do rơi xuống sông\n2)「酒・賭け事...」におぼれる。\nSa vào rượu chè/ cờ bạc.\n',
    deck: '4',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '143',
    front: '痛む',
    hiraganaReading: 'いたむ',
    hanChineseReading: 'THỐNG',
    meaning: 'bị đau',
    example:
        '１)『歯・頭・足。。。』が痛む。\nbị đau răng/đầu/chân...\n2)苦しんでいる友人のことを思うと、心が痛む。\nCảm thấy đau lòng khi nghĩ về người bạn đang vất vả .\n',
    deck: '4',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '144',
    front: 'かかる',
    hiraganaReading: 'かかる',
    hanChineseReading: '',
    meaning: 'Bị/ mắc',
    example: '1)インフルエンザにかかって、学校を休んだ \nBị Cúm nên đã nghỉ học\n',
    deck: '4',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '145',
    front: '酔う',
    hiraganaReading: 'よう',
    hanChineseReading: 'TÚY',
    meaning: 'Say',
    example:
        '1)酒に酔う。\nSay rượu\n2)酔った勢いで、好きな人に告白した。\nTỏ tình với người mình thích trong trạng thái say xỉn\n3)夫はぐでんぐでんに酔っ払って帰ってきた。\nÔng chồng lúc nào cũng về nhà trong trạng thái say khướt.\n4)駅で酔っ払いが騒いでる Mấy tên say đang làm náo động ở ga.\n5)車にようので、バス旅行に行けないのが残念だ\nVì bị say xe nên rất tiếc là không thể đi du lịch bằng xe bus được.\n6)観客はその歌手のすばらしい歌に酔っていた\nNgười nghe say mê/ yêu thích ca khúc tuyệt vời của ca sỹ đó\n7)彼は成功に酔った\n Anh ta mải mê với sự thành công.\n',
    deck: '4',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '146',
    front: '吐く',
    hiraganaReading: 'はく',
    hanChineseReading: '',
    meaning: 'Nôn, thở',
    example:
        '1) 息を吸って吐く。\nHít vào thở ra.\n2) 悪いものを食べたのか、胃の中のものを全部吐いてしまっ\nKhông biết có phải là ăn phải đồ ôi thiu không mà nôn hết tất cả ra rồi.\n3) 火山が煙を吐き出す \nNúi lửa phun khói\n',
    deck: '4',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '147',
    front: '診る',
    hiraganaReading: 'みる',
    hanChineseReading: 'CHẨN',
    meaning: 'Khám bệnh',
    example:
        '1) 体の調子が悪いので医者に診てもらおう\nTình trạng cơ thể mỏi mệt nên muốn đến bác sỹ khám bệnh.\n2) 医者が患者に診る\nBác sỹ khám bệnh cho bệnh nhân\n',
    deck: '4',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '148',
    front: '見舞う',
    hiraganaReading: 'みまう',
    hanChineseReading: 'KIẾN, VŨ',
    meaning: 'Thăm hỏi',
    example:
        '1) 入院中の友達をみんなで見舞った。\nTất cả mọi người đều đến thăm hỏi người bạn trong lúc nằm viện.\n2) ここはたびたび台風に見舞われる地域\nĐây là khu vực mà thỉnh thoảng bão lại đổ bộ vào.\n3) 『災害・災難』に見舞われる。\n Bị thiệt hại, thiên tai\n',
    deck: '4',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '149',
    front: '勤める',
    hiraganaReading: 'つとめる',
    hanChineseReading: 'CẦN',
    meaning: 'Làm việc',
    example:
        '1) 会社に勤める\n Làm việc tại công ty.\n2) 定年まで無事に勤め上げ\nHoàn thành mọi việc đến khi nghỉ hưu (không xảy ra sơ suất gì)\n',
    deck: '4',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '150',
    front: '稼ぐ',
    hiraganaReading: 'かせぐ',
    hanChineseReading: 'GIÁ',
    meaning: 'Kiếm (tiền)',
    example:
        '1) 大学時代はアルバイトで学費を稼い\nKiếm tiền - học phí bằng cách làm thêm hồi còn đại học.\n2) 一日一万円稼ぐのは大変 \nMột ngày có thể kiếm được 1 man thì thật là vất vả.\n3) 読解は苦手なので、日本語 能力試験では聴解で点をかせごうと思う\nVì khả năng đọc hiểu kém nên dự định kiếm điểm trong bài thi kiểm tra năng lực tiếng Nhật ở bài nghe hiểu.\n4) 出演者の到着が遅れ、その間、司会者が話しをして時間を稼ぐ。\nTrong lúc người biểu diễn đến muộn, người dẫn chương trình đã cầu giờ bằng một vài câu chuyện\n',
    deck: '5',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '151',
    front: '支払う',
    hiraganaReading: 'しはらう',
    hanChineseReading: 'CHI PHẤT',
    meaning: 'Thanh toán',
    example:
        '1) 買い物代金をカードで支払う。\nThanh toán tiền mua đồ bằng thẻ.\n2) 給料は銀行振り込むで支払われる。\nLương được thanh toán bằng cách chuyển khoản\n',
    deck: '5',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '152',
    front: '受け取る',
    hiraganaReading: 'うけとる',
    hanChineseReading: 'THỤ THỦ',
    meaning: 'Nhận',
    example:
        '1) 着払いの荷物を、代金を払って受け取った。\nThanh toán tiền mặt khi giao hàng và nhận hành lý.\n2) 大学から合格通知を受け取った。\nNhận thông báo trúng tuyển từ đại học.\n3) 上司からの注意は、自分への期待だと受け取ることにしている。\nTôi coi sự nhắc nhở từ cấp trên là sự kì vọng đối với tôi.\n',
    deck: '5',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '153',
    front: '払い込む',
    hiraganaReading: 'はらいこむ',
    hanChineseReading: 'PHẤT NHẬP',
    meaning: 'Nộp, đóng tiền',
    example: '1) 今期の授業料を銀行に払い込む。\nNộp học phí kì này qua ngân hàng.\n',
    deck: '5',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '154',
    front: '払い戻す',
    hiraganaReading: 'はらいもどす',
    hanChineseReading: 'PHẤT LỆ',
    meaning: 'Hoàn trả',
    example:
        '1) 電話会社は過大請求額を利用者の口座に払い戻す。\nCông ty điện thoại đã hoàn trả lại số tiền trẩ quá mức vào tài khoản của người sử dụng.\n2) コンサートが中止になったのでチケット代の払い戻しが行われた。\nVì buổi hòa nhạc bị hoãn nên ban tổ chức đã tiến hành hoàn trả tiền vé.\n',
    deck: '5',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '155',
    front: '引き出す',
    hiraganaReading: 'ひきだす',
    hanChineseReading: 'DẪN XUẤT',
    meaning: 'Rút ra, lấy ra',
    example:
        '1) スポンサーから資金を引き出すのに成功した。\nTôi đã thành công trong việc kêu gọi vốn từ nhà tài trợ.\n2) やっと社長からOKの返事を引き出した。\nCuối cùng thì cũng lấy được sự đồng ý từ giám đốc.\n3) コーチは選手の才能を引き出した。\nHuấn luyện viên đã tìm được tài năng của các tuyển thủ.\n',
    deck: '5',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '156',
    front: '儲かる',
    hiraganaReading: 'もうかる',
    hanChineseReading: 'Trữ',
    meaning: 'Lãi, có lợi nhuận',
    example:
        '1) 株で100万円儲かった。\nTôi đã lãi 100 vạn yên từ cổ phiếu.\n2）この商売は儲かる。\nCông việc buôn bán này có lợi nhuận.\n',
    deck: '5',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '157',
    front: '儲ける',
    hiraganaReading: 'もうける',
    hanChineseReading: 'Trữ',
    meaning: '1) Kiếm lời  2) Có con',
    example:
        '1）彼は株で100万円儲けた。\nAnh ấy đã kiếm lời được 100 vạn yên từ cổ phiếu.\n2）事業で儲けた金を市に寄付した。\nTôi đã quyên tặng số tiền lời kiếm được từ dự án cho thành phố.\n3）結婚して子供を３人儲けた。\nTôi kết hôn và đã có 3 đứa con.\n',
    deck: '5',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '158',
    front: '落ち込む',
    hiraganaReading: 'おちこむ',
    hanChineseReading: 'Lạc',
    meaning: '1）Suy sụp  2）Giảm sút, hạ',
    example:
        '1）景気が落ち込んで、失業率が上がった。\nVì nền kinh tế suy sụp nên tỷ lệ thất nghiệp đã gia tăng.\n2）仕事でミスをして落ち込んだ。\nVì gây ra lỗi trong công việc nên tôi đã suy sụp.\n3）成績が落ち込む。\nThành tích giảm sút.\n',
    deck: '5',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '159',
    front: '売れる',
    hiraganaReading: 'うれる',
    hanChineseReading: 'Mại',
    meaning: '1) Bán chạy  2) Nổi tiếng',
    example:
        '1）このCDは100万枚売れたそうだ。\nĐĩa CD này hình như đã bán được 100 vạn chiếc.\n2) その新商品は飛ぶように売れた。\nSản phẩm mới này đã bán chạy như bay.\n3）M氏は今最も売れている作家の一人だ。\nNgài M là một tác giả cực kỳ nổi tiếng hiện nay.\n',
    deck: '5',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '160',
    front: '売り切れる',
    hiraganaReading: 'うりきれる',
    hanChineseReading: 'Mại, Thiết',
    meaning: 'Bán hết sạch',
    example:
        '1）そのコンサートのチケットは1時間で売り切れたそうだ。\nVé của buổi hòa nhạc kia hình như đã bán hết sạch trong vòng một giờ.\n',
    deck: '6',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '161',
    front: 'くっ付く',
    hiraganaReading: 'くっつく',
    hanChineseReading: 'phó',
    meaning: 'dính chặt, bám vào',
    example:
        '1) 磁石と磁石がくっついて離れない。\nNam châm và nam châm dính chặt vào nhau không rời.\n2) 靴の下にガムがくっついてしまった。\nKẹo cao su dính ở đế giày.\n3) ３才の娘はいつも私にくっ付いて、離れようとしない。\nCon gái 3 tuổi cứ dính chặt lấy tôi chẳng chịu rời ra chút nào.\n',
    deck: '6',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '162',
    front: 'くっ付ける',
    hiraganaReading: 'くっつける',
    hanChineseReading: 'phó',
    meaning: 'làm dính vào, ghép vào',
    example:
        '1) 机と机をくっ付けて並べた。\nGhép 2 chiếc bàn lại để xếp.\n2) ソファーが小さいので、互いに体をくっ付けて、座った。\nVì ghế nhỏ nên hãy ghép sát người lại với nhau và ngồi xuống.\n',
    deck: '6',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '163',
    front: '固まる',
    hiraganaReading: 'かたまる',
    hanChineseReading: 'cố',
    meaning: 'đông cứng, củng cố',
    example:
        '1) 液体にゼラチンを入れると固まってゼリになる。\nKhi cho gelatin vào, nước sẽ đông cứng lại và trở thành thạch.\n2) この町では公共施設は駅の周りに固まっている。\nỎ thành phố này, các công trình công công tập trung dày đặc ở xung quanh nhà ga.\n3) クラスでは同じっ国の人同士で固まらず、いろいろな国の人と話すようにしましょう。\n Trong lớp, các bạn cùng một nước không nên tụ tập thành một nhóm mà hãy cố gắng nói chuyện với các bạn nước khác.\n4) 基礎が固まってから、難しいことに挑戦したほうがいい。\nSau khi củng cố các kỹ năng cơ bản, nên thử thách với những điều khó hơn.\n\n',
    deck: '6',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '164',
    front: '固める',
    hiraganaReading: 'かためる',
    hanChineseReading: 'cố',
    meaning: 'làm cứng, tăng cường',
    example:
        '1) ジュースを固めてゼリを作った。\nLàm đông nước hoa quả rồi làm thạch.\n2) みんなンの荷物を部屋の隅に固めておいた。\nDồn tất cả hành lý vào trong góc phòng rồi để vào đó.\n3) 「基礎・決心・結束・方針…」を固める。\nCủng cố nền tảng, quyết tâm, liên kết, phương châm...\n4)「守り、国境」を固める。\nTăng cường bảo vệ biên giới quốc gia.\n5) チームにメンバーをベテランで固める。\nTăng cường thêm người có kinh nghiệm cho thành viên của đội.\n',
    deck: '6',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '165',
    front: '縮む',
    hiraganaReading: 'ちぢむ',
    hanChineseReading: 'xúc',
    meaning: 'thu nhỏ',
    example: '\n',
    deck: '6',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '166',
    front: '縮まる',
    hiraganaReading: 'ちぢまる',
    hanChineseReading: 'súc',
    meaning: 'bị thu gọn, nén lại',
    example:
        '1)マラソンの世界記録はだんだん縮まっている。\nKỷ lục maraton thế giới đang dần dần được rút ngắn.\n2)トップとの差が縮まって来た。\nKhoảng cách với vị trí cao nhất dần được thu hẹp.\n',
    deck: '6',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '167',
    front: '縮める',
    hiraganaReading: 'ちぢめる',
    hanChineseReading: 'súc',
    meaning: 'rút ngắn',
    example:
        '1)ズボンが長すぎたので少し丈を縮めた。\nVì quần quá dài nên tôi đã làm ngắn gấu quần đi một chút.\n2)2倍のランナーが1倍との『距離、差』を縮めた。\nVận động viên chạy thứ 2 đã rút ngắn cự li với vận động viên thứ nhất.\n',
    deck: '6',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '168',
    front: '沈む',
    hiraganaReading: 'しずむ',
    hanChineseReading: 'trầm',
    meaning: 'chìm',
    example:
        '1)台風で船が海に沈んだ。\nTàu đã bị chìm xuống biển vì bão.\n2)ダムの建設で村が水に沈んだ。\nDo xây dựng con đập mà ngôi làng bị chìm trong biển nước.\n3)｛気持ち/気分/気｝が沈む。\nCẩm giác/ tâm trạng chùng xuống.\n4)沈んだ｛表情/声/色｝\nBiểu cảm/ giọng nói/ màu sắc trầm lắng.\n',
    deck: '6',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '169',
    front: '沈める',
    hiraganaReading: 'しずめる',
    hanChineseReading: 'trầm',
    meaning: 'làm chìm',
    example:
        '1)台風が船を海に沈めてしまった。\nCơn bão đã làm đắm thuyền.\n2)このガラスは、水に沈めるを見えなくなる。\nCái kính này khi chìm trong nước thì không thấy gì cả.\n3)ソファーに深く体を沈めて座った。\nTôi thả "phịch" người xuống ghế sofa.\n',
    deck: '6',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '170',
    front: '下がる',
    hiraganaReading: 'さがる',
    hanChineseReading: 'hạ',
    meaning: 'hạ xuống',
    example:
        '1)電灯からひもが下がっている。\nDây điện rớt từ trên bóng đèn xuống đất.\n2）たこが木の 枝にぶら下がっている。\nCon diều lao xuống cành cây .\n\n',
    deck: '7',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '171',
    front: '下げる/提げる',
    hiraganaReading: 'さげる',
    hanChineseReading: 'HẠ／ĐỀ',
    meaning: '1) Hạ xuống, cúi xuống  2) Treo, cầm',
    example:
        '1）日差しが強いので、ブラインドを下げた。\nVì ánh mặt trời chói chang nên tôi đã hạ rèm xuống.\n2）「すみません」と頭を下げた。\nCúi đầu và nói lời xin lỗi.\n3）窓のそばに風鈴を下げた。\nTreo chiếc chuông gió cạnh bên cửa sổ.\n4）店のドアに「本日休業」の札を下げた。\nTreo bảng "hôm nay đóng cửa" trên cửa ra vào của cửa hàng.\n5）荷物に手に提げて持つ。\nCầm hành lý trong tay.\n6）肩からかばんを提げた。\nMang balo trên vai.\n',
    deck: '7',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '172',
    front: '転がる',
    hiraganaReading: 'ころがる',
    hanChineseReading: 'CHUYỂN',
    meaning: '1) Lăn, ngã, ngả lưng (giường, ghế...)  3) Nhiều, đầy rẫy',
    example:
        '1）ボールが転がる。\nQuả bóng lăn.\n2）坂道を転がって落ちた。\nNgã lăn ở đường dốc và bị rơi xuống dưới.\n3）ベットに転がって本を読んだ。\nNgả lưng xuống giường và đọc sách.\n4）山道に石がたくさん転がっている。\nCó rất nhiều đá ở con đường trên núi.\n5）そんな話はどこにでも転がっている。\nNhững câu chuyện kiểu như thế này ở đâu cũng đầy rẫy.\n',
    deck: '7',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '173',
    front: '転がす',
    hiraganaReading: 'ころがす',
    hanChineseReading: 'CHUYỂN',
    meaning: 'Lăn, làm đổ',
    example:
        '1）ボーリングの球を転がしてピンを倒す。\nLăn quả bóng bowling và làm đổ lọ pin.\n2）さいころを転がす。\nĐổ xúc xắc.\n3）手が当たってビールピンを転がしてしまった。\nVì va vào tay nên lỡ làm đổ mất chai bia.\n4）荷物は適当にその辺に転がしておいてください。\nHành lý thì vứt tạm vào góc kia.\n',
    deck: '7',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '174',
    front: '傾く',
    hiraganaReading: 'かたむく',
    hanChineseReading: 'KHUYNH',
    meaning: 'Nghiêng',
    example:
        '1）地震で塀が傾いてしまった。\nBức tường bị nghiêng vì động đất.\n2）日が傾くと、気温も下がってきた。\nMặt trời nghiêng bóng thì nhiệt độ cũng hạ xuống.\n3）議論するにつれ、人々の意見は反対に傾いてきた。\nCùng với việc thảo luận, ý kiến mọi người đều nghiêng về việc phản đối.\n4）経営の失敗により、会社が傾いた。\nCông ty nghiêng ngả vì thất bại trong kinh doanh.\n',
    deck: '7',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '175',
    front: '傾ける',
    hiraganaReading: 'かたむける',
    hanChineseReading: 'KHUYNH',
    meaning: '1) Làm cho nghiêng  2) Dốc, tập trung làm',
    example:
        '1）あの子はわからないことがあると、首を傾けるくせがある。\nĐứa trẻ đó có thói quen nghiêng đầu khi gặp vấn đề không hiểu.\n2）びんを傾けて中身を出した。\nNghiêng chai và đổ các thứ bên trong ra ngoài.\n3）彼は若いころから研究に情熱を傾けていた。\nTừ khi còn trẻ anh ấy đã dồn nhiệt huyết vào việc nghiên cứu.\n4）学生たちは先生の話に耳を傾けた。\nHọc sinh chúng tôi lắng nghe cẩn thận lời giảng của giáo viên.\n',
    deck: '7',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '176',
    front: '裏返す',
    hiraganaReading: 'うらがえす',
    hanChineseReading: 'LÝ PHẢN',
    meaning: 'Lật ngược',
    example:
        '1) この書類は書き終わったら、裏返して机の上に置いてください。\nSau khi viết xong tài liệu này thì lật ngược lại và đặt trên bàn.\n2) セーターを裏返しに着て外出してしまった。\nLỡ mặc áo trái đi ra ngoài.\n3) 机に置いた紙が風で裏返った。\nTờ giấy trên bàn bị lật ngược lại vì gió.\n',
    deck: '7',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '177',
    front: '散らかる',
    hiraganaReading: 'ちらかる',
    hanChineseReading: 'TÁN',
    meaning: 'Bừa bộn',
    example:
        '1)兄の部屋はいつも散らかっている。 \nPhòng của anh trai tôi lúc nào cũng bừa bộn.\n2)部屋に雑誌が散らかっている。\nTạp chí bày lung tung trong phòng.\n',
    deck: '7',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '178',
    front: '散らかす',
    hiraganaReading: 'ちらかす',
    hanChineseReading: 'TÁN',
    meaning: 'Làm bừa bộn',
    example:
        '1)うちの子はすぐに部屋を散らかしてしまう。\n Đứa con tôi ngay lập tức làm bừa bộn căn phòng.\n',
    deck: '7',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '179',
    front: '散らばる',
    hiraganaReading: 'ちらばる',
    hanChineseReading: 'TÁN',
    meaning: 'Rải rác',
    example:
        '1)路上にゴミが散らばっている。\n Rác bay lung tung trên đường.\n2)夜空に星が散らばっている。\n Những ngôi sao rải rác khắp bầu trời đêm.\n3)彼の子孫は日本中に散らばっている。\n Những đứa cháu của anh ấy sống rải rác khắp Nhật Bản.\n',
    deck: '7',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '180',
    front: '刻む',
    hiraganaReading: 'きざむ',
    hanChineseReading: 'KHẮC',
    meaning: '1) Thái, khắc  2) Ghi nhớ',
    example:
        '1) キャベツを刻んでいためる。\nThái bắp cải rồi xào.\n2) 時計が時を刻む。\n Đồng hồ ghi dấu thời gian.\n3) 石に文字を刻む。\nKhắc chữ lên đá.\n4) 大きな岩を刻んで仏像を彫る。\nXẻ tảng đá lớn ra rồi khắc thành bức tượng Phật.\n5) 父の言葉を胸に刻む。\nKhắc ghi lời dạy của cha trong trái tim.\n6) 祖母の顔には深いしわが刻まれていた。\n6) Nếp nhăn khắc sâu trên khuôn mặt bà.\n',
    deck: '8',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '181',
    front: '挟まる',
    hiraganaReading: 'はさまる',
    hanChineseReading: 'HIỆP',
    meaning: 'Kẹp, kẹt',
    example:
        '1) コートが電車のドアに挟まって 抜けない\nÁo khoác bị kẹt ở cửa tàu điện không rút ra được.\n2) 会社で上司と部下の間に挟まって、彼女は苦労しているようだ。\nCô ấy có vẻ rất khó xử vì kẹt giữa cấp trên và cấp dưới ở công ty.\n',
    deck: '8',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '182',
    front: '挟む',
    hiraganaReading: 'はさむ',
    hanChineseReading: 'HIỆP',
    meaning: '1) Kẹp vào,  2) Chèn vào',
    example:
        '1) 電車のドアに挟まれないようご注意ください。\nChú ý để không bị kẹp vào cửa của tàu điện.\n2) パンにハムと卵を挟む。\nKẹp giăm bông (giò) và trứng vào bánh mỳ.\n3) 彼はすぐ人の話に横から口を挟むので困る。\nAnh ta rất là rắc rối vì hay chen ngang vào câu chuyện của người khác.\n',
    deck: '8',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '183',
    front: 'つぶれる',
    hiraganaReading: 'つぶれる',
    hanChineseReading: '',
    meaning: '1) Bị nghiền nát, bị bẹp  2) Bị mất, bị phá sản.',
    example:
        '1) 箱が 落ちて、中のケーキがつぶれてしまった。\nChiếc hộp rơi xuống đất nên bánh bên trong bị vỡ nát hết.\n2) 資金不足で計画がつぶれてしまった。\nVì thiếu tiền đầu tư nên kế hoạch đã bị phá sản.\n3) せっかくのチャンスがつぶれてしまった。\nTôi đã bị mất cơ hội quý giá.\n4) 会社がつぶれた。\nCông ty đã bị phá sản.\n5) 会議で半日つぶれてしまった。\nVì cuộc họp mà mất toi nửa ngày.\n',
    deck: '8',
  ),
  Flash_Card(
    knowledge: 'Chua hoc',
    id: '184',
    front: 'つぶす',
    hiraganaReading: 'つぶす',
    hanChineseReading: '',
    meaning: '1) Làm mất, làm cho phá sán  2) Nghiền  3) Giết (thời gian )',
    example:
        '1) ゆでたじゃがいもをつぶしてサラダを作った。\nTôi nghiền nát khoai tây luộc để làm món Salad.\n2) 空き缶やペットボトルは、つぶしてからゴミに出すとよい。\nChúng ta nên đập dẹp lon và chai nhựa rỗng rồi hẵn vứt chúng.\n3) せっかくのチャンスをつぶしてしまった。 \nTôi đã phá hỏng cơ hội hiếm có.\n彼、経営力のなさから会社をつぶしてしまった。\nDo anh ta không có năng lực quản lý nên đã khiến công ty phá sản.\n4) 友達を持っている間、本屋で時間をつぶした。\nTrong lúc đợi bạn, tôi vào hiệu sách để giết thời gian.\n',
    deck: '8',
  ),
];
